# Generated by Django 5.2.4 on 2025-09-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('US', 'United States'), ('BR', 'Brazil'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('FR', 'France'), ('DE', 'Germany'), ('IN', 'India'), ('JP', 'Japan'), ('CN', 'China')], max_length=100, null=True)),
            ],
        ),
    ]
